name: Deploy to Github Pages

on:
  workflow_dispatch: # allow manually running
  push:
    branches: ["master"] # run on pushes

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: DeterminateSystems/nix-installer-action@v4

    - uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: "Build site"
      run: "nix build -o _site"

    - name: Upload built site
      uses: actions/upload-pages-artifact@v1

    - name: Deploy to gh-pages
      uses: actions/deploy-pages@v1.2.3
