name: Deploy to Github Pages

on:
  workflow_dispatch: # allow manually running
  push:
    branches: ["master"] # run on pushes

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Jekyll build
      run: |
        docker build . --tag=image
        docker run -e JEKYLL_ENV=production \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          image jekyll build

    - name: Upload built site
      uses: actions/upload-pages-artifact@v1

    - name: Deploy to gh-pages
      uses: actions/deploy-pages@v1.2.3
