name: Deploy to Github Pages

on:
  workflow_dispatch: # allow manually running
  push:
    branches: ["master"] # run on pushes

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_ralismark_xyz:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: DeterminateSystems/nix-installer-action@v4

    - uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: "Build site"
      run: "nix run . -- build -o _site site/main.py"

    - name: Upload built site
      uses: actions/upload-pages-artifact@v1

    - name: Deploy to gh-pages
      uses: actions/deploy-pages@v1.2.3

  build_kwellig_garden:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: DeterminateSystems/nix-installer-action@v4

    - uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: "Build site"
      run: "nix run . -- build -o _site kwellig.garden/main.py"

    - name: "Deploy to kwellig.garden"
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy _site --project-name=kwellig-garden
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
