name: Deploy

on:
  workflow_dispatch: # allow manually running
  push:
    branches: ["master"] # run on pushes

permissions:
  contents: read
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build_kwellig_garden:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - uses: rrbutani/use-nix-shell-action@v1
      with:
        devShell: .#ci

    - name: "Build site"
      run: "heron build -o dist kwellig.garden/_heron.py"

    - name: "Deploy to kwellig.garden"
      run: "wrangler deploy"
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
