name: Deploy to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Jekyll build
      run: |
        docker build . --tag=image
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          image jekyll build

    - name: Push to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # This is the branch you wish to deploy to, for example gh-pages or
        # docs.
        BRANCH: gh-pages
        # The folder in your repository that you want to deploy. If your build
        # script compiles into a directory named build you would put it here.
        # Folder paths cannot have a leading / or ./. If you wish to deploy the
        # root directory you can place a . here.
        FOLDER: _site
        # This option can be used if you'd prefer to have a single commit on
        # the deployment branch instead of maintaining the full history.
        SINGLE_COMMIT: true
