name: Deploy

on:
  workflow_dispatch: # allow manually running
  push:
    branches: ["master"] # run on pushes

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_kwellig_garden:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - uses: rrbutani/use-nix-shell-action@v1
      with:
        devShell: .#ci

    - name: "Build site"
      run: "heron build -o _site kwellig.garden/_heron.py"

    - name: "Deploy to kwellig.garden"
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy _site --project-name=kwellig-garden
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
